### ISSUE TITLE
successfully produced the .gz file despite encountering error

### ISSUE THREAD

**Issue by tranhoangnguyen03** [nikvdp/agentgrunt#1]
Preparing to build 'git_repo'...
Downloading git binary: 100%|██████████████| 65.5M/65.5M [00:00<00:00, 120MiB/s]
Compressing source dir: 100%|█████████████████| 43/43 [00:02<00:00, 16.66file/s]
Wrote archive to: /content/git_repo.tar.gz

Please upload this file to ChatGPT, and paste the following message into the chat:

---
Please extract the archive I've uploaded to /tmp, read the contents of tools_for_ai/README_ai.md in it's entirety, and follow the directions listed inside that file.
---
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/agentgrunt/main.py:110 in bundle     │
│                                                                              │
│   107 │   print(final_msg)                                                   │
│   108 │   print(f"---\n{gpt_prompt}\n---")                                   │
│   109 │                                                                      │
│ ❱ 110 │   if interactive and local.which("pbcopy"):                          │
│   111 │   │   # prompt user if they want to copy it and reveal the file, the │
│   112 │   │                                                                  │
│   113 │   │   copy = (                                                       │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │           assume_yes = False                                             │ │
│ │            clone_url = 'file:///content/git_repo'                        │ │
│ │          destination = PosixPath('/content/git_repo.tar.gz')             │ │
│ │            final_msg = 'Wrote archive to:                                │ │
│ │                        /content/git_repo.tar.gz\n\nPlease upload this    │ │
│ │                        file to ChatGPT, '+47                             │ │
│ │ git_binary_dest_path = PosixPath('/root/.cache/agentgrunt/git_binary/gi… │ │
│ │       git_binary_url = 'https://github.com/nikvdp/1bin/releases/downloa… │ │
│ │        git_cache_dir = PosixPath('/root/.cache/agentgrunt/git_binary')   │ │
│ │           gpt_prompt = "Please extract the archive I've uploaded to      │ │
│ │                        /tmp, read the contents of tools_for"+85          │ │
│ │        gpt_tools_dir = PosixPath('/usr/local/lib/python3.10/dist-packag… │ │
│ │          interactive = True                                              │ │
│ │           output_dir = PosixPath('/tmp/tmpl4s7c_vc')                     │ │
│ │     preserve_history = False                                             │ │
│ │            repo_name = 'git_repo'                                        │ │
│ │           short_name = 'git_repo'                                        │ │
│ │             src_repo = 'git_repo'                                        │ │
│ │              tarball = PosixPath('/tmp/tmp1a26vbuo.tar.gz')              │ │
│ │         tarball_path = PosixPath('/tmp/tmp1a26vbuo.tar.gz')              │ │
│ │            temp_repo = PosixPath('/tmp/tmpva98u4rv')                     │ │
│ │        user_code_dir = PosixPath('/tmp/tmpl4s7c_vc/uc')                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/plumbum/machines/local.py:203 in     │
│ which                                                                        │
│                                                                              │
│   200 │   │   │   if path:                                                   │
│   201 │   │   │   │   cls._program_cache[key] = path                         │
│   202 │   │   │   │   return path                                            │
│ ❱ 203 │   │   raise CommandNotFound(progname, list(cls.env.path))            │
│   204 │                                                                      │
│   205 │   def path(self, *parts):                                            │
│   206 │   │   """A factory for :class:`LocalPaths <plumbum.path.local.LocalP │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │ alternatives = ['pbcopy']                                                │ │
│ │          cls = <class 'plumbum.machines.local.LocalMachine'>             │ │
│ │          key = (                                                         │ │
│ │                │   'pbcopy',                                             │ │
│ │                │                                                         │ │
│ │                '/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr… │ │
│ │                )                                                         │ │
│ │         path = None                                                      │ │
│ │           pn = 'pbcopy'                                                  │ │
│ │     progname = 'pbcopy'                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
CommandNotFound: (CommandNotFound(...), 'pbcopy', [<LocalPath /opt/bin>, 
<LocalPath /usr/local/nvidia/bin>, <LocalPath /usr/local/cuda/bin>, <LocalPath 
/usr/local/sbin>, <LocalPath /usr/local/bin>, <LocalPath /usr/sbin>, <LocalPath 
/usr/bin>, <LocalPath /sbin>, <LocalPath /bin>, <LocalPath /tools/node/bin>, 
<LocalPath /tools/google-cloud-sdk/bin>])

**Comment by nikvdp** [comment]
Hi @tranhoangnguyen03, thanks for the catching that! Fixed in https://github.com/nikvdp/agentgrunt/commit/9a5c8765c98e4cb4456385ef67518a45083c122b. It was an issue with the way I was checking for the availability of `pbcopy` which caused it to bundle everything successfully but then die when trying to to copy the prompt to the clipboard. You can grab the latest version with the fix by doing `pip install --ugprade agentgrunt`.
